:bug: Eventshub receiver readiness ensured
knative-sandbox/reconciler-test pull request #284
Opened 2022-01-17 12:28 UTC by cardil

# Changes

- :bug: Eventshub receiver readiness ensured

/kind bug

Fixes #270
Closes #271

2022-01-19 16:56 UTC, lionelvillard commented
/test pull-knative-sandbox-reconciler-test-integration-tests

2022-01-26 23:14 UTC, cardil commented
/test pull-knative-sandbox-reconciler-test-integration-tests

2022-01-27 07:20 UTC, pierDipi requested changes
I'm facing this issue, thanks for the fix!

2022-01-27 07:20 UTC, pierDipi commented on pkg/k8s/job.go
> +				log.Debugf("%s/%s job %+v", namespace, name, err)
Why this? We want to have test-scoped logs.

/hold

2022-01-27 07:31 UTC, pierDipi commented on pkg/logging/context.go
> +}
The logger created here won't be bound to a `testing.T` variable, so we don't get test-scoped logs.

2022-01-27 12:15 UTC, cardil commented on pkg/logging/context.go
> +}
That's right. The logging is all over the place (`t.Log`, `zap`, `fmt.Print`, `log`, `k8s.io/klog`) I plan to refactor it all to use [`zaptest.NewLogger`](https://pkg.go.dev/go.uber.org/zap/zaptest#NewLogger) - that will bound all messages to `testing.T`.

But, maybe we could do that in separate PR, WDYT?

2022-01-27 13:36 UTC, pierDipi commented on pkg/logging/context.go
> +}
+1, that would be great!

We should inject the logger in the context when `MagicEnvironment.Test(...)` is called.

My only concern of this PR is that, [as per my previous comment](https://github.com/knative-sandbox/reconciler-test/pull/284#discussion_r793311633), bring a regression in terms of logging scope, so I'd say let's revert that and work on the refactoring in a separate PR.

2022-01-27 15:50 UTC, cardil commented on pkg/logging/context.go
> +}
I've refactored the logging in 5768204.

Maybe we can do it in one PR?!?

2022-01-27 18:43 UTC, cardil commented on pkg/logging/context.go
> +}
Hmm, on second thought, I think I'll divide this PR, and create a second one targeted solely on logging.

2022-01-27 19:18 UTC, cardil commented on pkg/logging/context.go
> +}
Opened the #294 for logging overhoul

2022-01-27 19:45 UTC, cardil commented on pkg/k8s/job.go
> +				log.Debugf("%s/%s job %+v", namespace, name, err)
Restored in fea507b

Moved to #294

/unhold

2022-01-28 08:01 UTC, pierDipi approved these changes
/lgtm

/hold in case you want to address my comments regarding the image

2022-01-28 08:01 UTC, pierDipi commented on pkg/k8s/wait.go
> +const ubi8Image = "registry.access.redhat.com/ubi8/ubi"
Maybe we can use centos?

2022-01-28 09:37 UTC, cardil commented on test/e2e/eventshub/receiver_readiness.go
> +const ubi8Image = "registry.access.redhat.com/ubi8/ubi"
Ubi image is exactly the same legal situation as using CentOS stream or Fedora. All of the are free for use by any party (community or software vendor). I don't see a reason to switch.

From https://catalog.redhat.com/software/containers/ubi8/ubi/5c359854d70cc534b3a3784e?container-tabs=gti:

> The Red Hat Universal Base Image is free to deploy on Red Hat or non-Red Hat platforms and freely redistributable. Software vendors and community projects which build on UBI may have additional EULAs which apply to their layered software. Please refer to the End User License Agreement for the Red Hat Universal Base Image for information about use of the Red Hat Universal Base Image and associated software and source code.

2022-01-28 09:39 UTC, cardil commented on test/e2e/eventshub/receiver_readiness.go
> +const ubi8Image = "registry.access.redhat.com/ubi8/ubi"
And using UBI we should avoid potential problems with docker.io download quotas.

2022-01-28 10:48 UTC, pierDipi commented on test/e2e/eventshub/receiver_readiness.go
> +const ubi8Image = "registry.access.redhat.com/ubi8/ubi"
Ok, cool!

/unhold

2022-01-28 10:50 UTC, cardil commented
/approve

2022-01-28 10:51 UTC, cardil commented
:sob: Permission not propagated yet https://github.com/knative/community/pull/910

2022-01-28 12:22 UTC, cardil commented
/assign @knative-sandbox/productivity-writers

2022-02-01 13:26 UTC, cardil commented
/assign @chizhg

2022-02-01 21:52 UTC, chizhg commented
/approve

2022-02-01 22:05 UTC, merged