Wait for resource deletions in DeleteResources
knative-sandbox/reconciler-test pull request #288
Opened 2022-01-26 15:17 UTC by pierDipi

This patch makes the method `f.DeleteResources` semantic more
clear by waiting for all resources to be deleted before returning.

This guarantees that once a feature passed to a next phase
resources were actually deleted.

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

2022-01-26 15:18 UTC, pierDipi commented
/assign @lionelvillard @devguyio

2022-01-26 20:49 UTC, pierDipi commented on pkg/feature/logging.go
> +Copyright 2020 The Knative Authors
```suggestion
Copyright 2022 The Knative Authors
```

2022-01-26 20:55 UTC, pierDipi commented
/cherry-pick release-1.2

2022-01-28 10:26 UTC, cardil requested changes
I've made a review on the other PR - https://github.com/knative-sandbox/reconciler-test/pull/293#pullrequestreview-865933914. Most of those comments refer here.

2022-02-02 15:32 UTC, lionelvillard commented
@pierDipi @cardil is this ready to go?

2022-02-02 15:34 UTC, pierDipi commented
I think it's ready

2022-02-02 15:47 UTC, cardil approved these changes
Approving both this and #293 based on comment: https://github.com/knative-sandbox/reconciler-test/pull/293#pullrequestreview-870736531

/lgtm
/approve

2022-02-02 15:59 UTC, merged