Wait pod running prints non-ready pod logs
knative-sandbox/reconciler-test pull request #292
Opened 2022-01-27 07:09 UTC by pierDipi

Logging pod logs of unhealthy pods helps debug test issues.

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

2022-01-27 07:09 UTC, pierDipi commented
/assign @lionelvillard @devguyio

2022-01-28 10:23 UTC, cardil requested changes

2022-01-28 10:23 UTC, cardil commented on pkg/k8s/wait.go
> +			}
Could we rewrite this to dump the logs to a report file (within `$ARTIFACTS` dir) and log only a link to the file dumped? Similar to: https://github.com/cardil/knative-reconciler-test/blob/52949cd7a6a198ff682dee561f87829fb227f3b6/pkg/milestone/emitter_log.go#L128-L141

Putting so much information on console makes log browsing a pain.

2022-02-02 15:36 UTC, pierDipi commented on pkg/k8s/wait.go
> +			}
unready pods don't have many logs, anyway I'll revisit this in the future, so closing

/close

2022-02-02 15:36 UTC, closed without merging