Auto logging on teardown
knative-sandbox/reconciler-test pull request #293
Opened 2022-01-27 07:14 UTC by pierDipi

The existing tests framework in eventing has the nice feature
of logging resources that are tracked during a test and that's
helpful for debugging test issues.

This PR is adding support for the same feature, by automatically
prepending logging steps to the teardown phase of every feature.

Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>

/hold this PR is based on https://github.com/knative-sandbox/reconciler-test/pull/288

2022-01-28 10:18 UTC, cardil requested changes
Nice idea! Looks good apart from few comments. 

Please respond to comments, with your opinion, so we could resolve them.

2022-01-28 10:18 UTC, cardil commented on pkg/feature/logging.go
> +}
Could we rewrite this method to dump those objects to a report file (within `$ARTIFACTS` dir) and log only a link to the file and number of objects dumped? Similar to: https://github.com/cardil/knative-reconciler-test/blob/52949cd7a6a198ff682dee561f87829fb227f3b6/pkg/milestone/emitter_log.go#L128-L141

Putting everything on console makes log browsing a pain.

2022-01-28 10:18 UTC, cardil commented on pkg/feature/feature.go
> +	err := wait.Poll(time.Second, 4*time.Minute, func() (bool, error) {
Maybe take timing from `context.Context`?

2022-01-28 10:18 UTC, cardil commented on pkg/environment/logging.go
> +	}
```suggestion
	return []feature.Step{{
		Name: "Log references",
		S:    feature.Any,
		L:    feature.Must,
		T:    feature.Teardown,
		Fn:   feature.LogReferences(mr.refs...),
	}}
```

2022-01-28 10:18 UTC, cardil commented on pkg/environment/logging.go
> +// loggingSteps returns a number of steps that logs ma
The sentence in this comment seams not finished

2022-01-28 10:18 UTC, cardil commented on pkg/environment/magic.go
> +	steps[feature.Teardown] = append(mr.loggingSteps(), steps[feature.Teardown]...)
This means that the objects will be dumped even if tests passes. It would be good to dump them only if test failed.

2022-01-28 15:53 UTC, pierDipi commented on pkg/environment/magic.go
> +	steps[feature.Teardown] = append(mr.loggingSteps(), steps[feature.Teardown]...)
Logging in tests isn't actually printed in the failed test case if the test doesn't use the `verbose` logging flag

2022-01-28 15:54 UTC, pierDipi commented on pkg/environment/logging.go
> +// loggingSteps returns a number of steps that logs ma
:man_facepalming:

2022-01-28 15:55 UTC, pierDipi commented on pkg/environment/logging.go
> +// loggingSteps returns a number of steps that logs ma
```suggestion
// loggingSteps returns a number of steps that logs environemnt managed resources.
```

2022-01-28 15:57 UTC, pierDipi commented on pkg/feature/feature.go
> +	err := wait.Poll(time.Second, 4*time.Minute, func() (bool, error) {
Unfortunately, there is a cyclic dependency between the packages, `environment` imports `feature` and `feature` can't import `environment` to pull timings, so I wanted to re-org packages in a separate PR

2022-01-28 16:01 UTC, pierDipi commented on pkg/feature/logging.go
> +}
While working at debugging failed tests I found debugging a lot easier and quicker when logs are immediately searchable, navigating artifacts files should be the last resort for really deep insights and weird bugs.

Also, having logs immediately searchable lowers the barrier for new contributors who don't have a clear understanding of where things are, so I'd prefer logging them directly.

2022-01-28 16:05 UTC, pierDipi commented on pkg/feature/logging.go
> +}
This is also the behavior that we already have in eventing core testing libraries, so people are already familiar with that.

2022-01-28 16:07 UTC, pierDipi commented on pkg/environment/magic.go
> +	steps[feature.Teardown] = append(mr.loggingSteps(), steps[feature.Teardown]...)
However, let me add a check originalT.Failed().

2022-01-28 16:07 UTC, pierDipi commented on pkg/environment/magic.go
> +
```suggestion
	if originalT.Failed() {
		// Prepend logging steps to the teardown phase.
		steps[feature.Teardown] = append(mr.loggingSteps(), steps[feature.Teardown]...)
	}

```

2022-01-28 16:08 UTC, pierDipi commented on pkg/environment/magic.go
> +	steps[feature.Teardown] = append(mr.loggingSteps(), steps[feature.Teardown]...)
Done

2022-01-28 17:50 UTC, pierDipi commented on pkg/feature/logging.go
> +}
I disagree as stated in my previous comments, I spent quite a lot of time debugging failed tests, it is slow to look at the uploaded logs.

Even if library users want this behavior (and I don't) they can provide their own implementation of `feature.T` that forwards the logs to a file but this has to be opt-in.

2022-01-28 17:53 UTC, pierDipi commented on pkg/feature/logging.go
> +}
and trust me, every eventing event that is logged in the console has been useful to root cause failed tests, so I don't see them as cluttering the console but just providing enough material to debug tests.

2022-02-01 16:20 UTC, cardil commented on pkg/feature/logging.go
> +}
This been discussed here, and accepted https://github.com/knative/eventing/issues/4592

2022-02-02 15:42 UTC, cardil commented on pkg/feature/logging.go
> +}
I think we should survey the community on how we should proceed with test output.

For example, we are running tests with `-v` to see the non-crucial results, like the unavailability time during upgrades. Dumping too much when it's not needed (test pass) makes it harder to browse the logs, and also make the execution slower.

I'll accept it for now. And we will go back to this in separate PR.  (probably #294)

2022-02-02 15:44 UTC, cardil approved these changes
It looks ok to me, apart from https://github.com/knative-sandbox/reconciler-test/pull/293/files#r797742084 (but we can continue on that issue in separate PR)

/lgtm
/approve

2022-02-02 16:20 UTC, cardil commented
/hold cancel

2022-02-15 01:53 UTC, cardil approved these changes
/lgtm

2022-02-15 02:06 UTC, merged