Refactoring feature steps execution
knative-sandbox/reconciler-test pull request #97
Opened 2021-02-17 13:58 UTC by slinkydeveloper

This PR revisits the way tests are executed and introduces some constraint on what can be executed inside the `StepFn`.

## The `feature.T` interface

The most important (and breaking) change is the `feature.T` interface. A `StepFn` now can fail, err, skip and log but it cannot create a subtest nor do other fancy stuff. This constrain a bit the step capabilities, in order to "force" users to create different feature steps.

## The new step fn execution

Now the step fn (you can check it out in `magic.go`) doesn't run anymore in `t.Run`, but we manually run the stepFn in a specific goroutine that makes sure:

* context is properly handled per step-fn
* steps are executed in order
* one step fn cannot influence the execution of other step fn

I believe this approach gives us greater flexibility (check the TODO on test failure) and removes some race conditions (like https://github.com/knative/eventing/issues/4637 and the https://github.com/knative-sandbox/reconciler-test/pull/52).

To make sure our infra understands the results, I've adapted the output to the go test output.

2021-02-17 13:59 UTC, slinkydeveloper commented
cc @n3wscott @dprotaso @vagababov

2021-02-24 21:12 UTC, dprotaso reviewed
> skip and log but it cannot create a subtest nor do other fancy stuff. 

why do you want to restrict it?

2021-02-24 21:12 UTC, dprotaso commented on pkg/environment/magic.go
> +		testingT.Logf("Timeout exceeded")
Also given [`-timeout` panics](https://golang.org/cmd/go/#hdr-Testing_flags)
>  If a test binary runs longer than duration d, panic.

I wonder if we can _even_ this clean up will occur

2021-02-24 21:12 UTC, dprotaso commented on pkg/feature/t.go
> +type T interface {
There's probably more that are useful

ie. Cleanup,Deadline,Helper etc.

2021-02-24 21:17 UTC, dprotaso commented on pkg/environment/magic.go
> +	<-ctx.Done()
Since this waits for the test to finish why use a go routine at all?

2021-02-24 21:17 UTC, dprotaso commented on pkg/environment/magic.go
> +		}
re: mutliple features being executed

https://github.com/knative-sandbox/reconciler-test/pull/102

2021-02-25 15:13 UTC, n3wscott requested changes
There are several improvements we should cherrypick out of this PR but overall I really really really do not want to change the signature for `StepFn` to force providers of StepFn impls to need to vendor this lib. 

I think the timing things are very complicated and I have not seen a need to do more than what standard golang testing is doing today.

Controlling the output seems like a direct user feedback thing that is nice but not necessary. 

I would rather think about how to collect the results and then provide them as a file and/or printed at the end of the test run to give tooling a structured way to look at results over trying to make the output easier to read for a human.

Overall, our goal here is not to be fancy, we need to focus on the UX of writing tests and having them be as vendorable, composable, and repeatable as possible while not needing to teach any new ways to control tooling or significantly change how the code is written. 

Better or worse, go choose to use the struct `*testing.T` and I really do not want to be in the business of wrapping, shimming or playing catchup as new features come from that area.

2021-02-25 15:13 UTC, n3wscott commented on pkg/environment/t.go
> +type t struct {
Why is this needed?

2021-02-25 15:13 UTC, n3wscott commented on pkg/feature/t.go
> +type T interface {
I really don't want to define this interface.

2021-02-25 15:13 UTC, n3wscott commented on pkg/feature/feature.go
> +type StepFn func(ctx context.Context, t T)
hard no thank you on this one. The whole point of using `*testing.T` is I can define a set of steps and not depend on this library at all. I don't want to force an interface here, I really just want it to be a standard testing.T object.

2021-02-25 15:13 UTC, n3wscott commented on pkg/environment/magic.go
> +	var cancelFn context.CancelFunc
This all looks very complicated and I don't see why it would be better than letting the testing lib do this work.

2021-03-01 09:39 UTC, slinkydeveloper commented
Ok so I admit there are some several points in this PR that I got in my mind while working on it, so let me try to go through it step by step:

> I really don't want to define this interface.

About the `feature.T` interface, the main reason behind it is to avoid users to do `t.RunTest`. First and most important, `RunTest` inside a `StepFn` doesn't make sense, or you have different `Assert` steps or you have different `Feature`s.
Also, if you execute `t.RunTest` inside a StepFn, it can break everything regarding . go testing doesn't care about setup, requirement, assert and teardown, even less it cares about our context, our execution order etc. https://stackoverflow.com/questions/31201858/how-to-run-golang-tests-sequentially . Since today we have the "steps collapse" I've implemented (which might be wrong and might not really solve cleanly the original problem), If I run inside a `Setup` a `t.RunTest`, the execution of the subtest might actually end after the callee `StepFn` completed the execution.

With this interface (which is drafted, i know, and it definitely requires Cleanup etc) we still have a `testing.T` compliant type, so it works with various `testify` and friends and, at the same time, forces our restrictions and gives us greater flexibility in future to change the underlying test execution code. We also have the control on test results and, thanks to that, we can have a custom report of the test results, like explained in the PR description. Having a detailed "compliance report" is one of the most important features we initially identified for this framework, and IMO parsing the test output will never give us the level of detail we want.
In other words, exposing `testing.T` in `StepFn` to me is like exposing the implementation detail that this library is relying on `go test` and this doesn't give us flexibility to implement all the things we want.

The test execution with all the various logging statements etc is a separate point from the `feature.T` interface (they can co-exist, or just `feature.T` can exist). I wrongly put both in the same PR. The idea of rewriting the test execution code was to force exactly our "guarantees" of the execution order, define specific policies when some phase fails. e.g. if a requirement or setup phase fails, the execution of the feature should not continue, but if a requirement step fail, maybe the test should not be flagged as failed but more as a skipped with the failure reason from the requirement phase (which brings me to the previous point of having a `feature.T` interface). Since go test doesn't give us the flexibility of failing/skipping/controlling the execution of tests directly based on the result of others, I tried to rewrite the bits from `testing` that we need to execute the testing code here

> to force providers of StepFn impls to need to vendor this lib.

I don't understand why this argument is a problem, since the user of this framework and of StepFn is going to depend on this framework anyway.

2021-03-02 16:39 UTC, n3wscott commented on pkg/feature/t.go
> +type T interface {
Ok, I talked offline with Slinky and we are going to keep the interface.

2021-03-02 16:44 UTC, slinkydeveloper commented
I'm closing this one since it's a mix of things and splitted the discussion:

* https://github.com/knative-sandbox/reconciler-test/issues/106
* https://github.com/knative-sandbox/reconciler-test/pull/105

2021-03-02 16:44 UTC, closed without merging

2021-03-02 16:46 UTC, n3wscott commented on pkg/feature/feature.go
> +type StepFn func(ctx context.Context, t T)
we are going to try it.